'use strict';
const state = { page:'overview', csrf:'', overview:null, setup:null, actions:{}, jobs:[], openJob:null, brokerSnapshot:null };
const $ = s => document.querySelector(s);
const escapeHTML = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = name => `<svg aria-hidden="true"><use href="#i-${name}"/></svg>`;
const fmtDate = value => { if (!value) return '—';const d = new Date(value);return Number.isNaN(d.getTime())?'—':d.toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}); };
const numeric = (v,digits=0) => v !== null && v !== undefined && v !== '' && Number.isFinite(Number(v)) ? Number(v).toLocaleString(undefined,{maximumFractionDigits:digits}) : '—';
const statusTag = (s, name) => { let kind = ['SUCCEEDED','COMPLETE','AVAILABLE','GREEN'].includes(s)?'':'tag-warn'; if (['FAILED','CRITICAL','INTERRUPTED','TIMED_OUT','NOT_AVAILABLE'].includes(s)) kind='tag-danger';if(['RUNNING'].includes(s))kind='tag-plain';if(['PENDING','EXTERNAL_REQUIRED'].includes(s))kind='tag-muted';return `<span class="tag ${kind}">${escapeHTML(name||s||'UNKNOWN')}</span>`; };
async function get(path) { const r=await fetch(path,{credentials:'same-origin',cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error||`Server ${r.status}`);return j; }
async function post(path, body) { const r=await fetch(path,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Alpha-CSRF':state.csrf},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error||`Server ${r.status}`);return j; }
function toast(message, error=false) { const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;$('#toasts').prepend(el);setTimeout(()=>el.remove(),6500); }
function emptyPanel(message,sub) {return `<div class="empty-plot"><div class="plot-icon">${icon('activity')}</div><strong>${escapeHTML(message)}</strong><small>${escapeHTML(sub)}</small></div>`;}
function ribbon() {return `<div class="ribbon"><div class="ribbon-left">${icon('shield')}<div><strong>Order execution is locked</strong><small>You may connect to Dhan for read-only account inspection. Alpha_OTO cannot buy, sell, transfer funds, withdraw, or charge a payment method.</small></div></div>${statusTag('RUNNING','NO ORDERS')}</div>`;}
function metric(label,val,description,ico,extra='') {return `<div class="metric"><div class="metric-head"><span class="metric-label">${label}</span>${icon(ico)}</div><div class="metric-value ${extra}">${val}</div><div class="metric-detail">${description}</div></div>`;}
function mainStats(o) {
 const f=o.forward||{};
 const complete=f.complete_forward_bars ?? 0;
 const researchReady=Object.values(o.reports||{}).filter(v=>v.present).length;
 const feeds=(o.series||[]).filter(v=>v.present).length;
 return `<div class="metrics-grid">
 ${metric('Connected markets',`${feeds}<span style="color:#64746a;font-size:14px"> / 2</span>`,'Historical crypto datasets','database')}
 ${metric('Forward evidence',numeric(complete),'New synchronized hourly observations','activity')}
 ${metric('Research reports',numeric(researchReady),'Verified local report files','brain')}
 ${metric('Live trading','LOCKED','Dhan connection is read-only','lock','smaller')}
 </div>`;
}
function panelHeader(title,desc,extra='') {return `<div class="panel-header"><div><h2>${title}</h2><p>${desc}</p></div>${extra}</div>`;}
function recentJobs(o) { const rows=(o.jobs||[]);return rows.length ? rows.slice(0,4).map(j=>`<div class="event"><div class="event-circle ${j.status==='FAILED'?'warn':''}">${icon(j.status==='RUNNING'?'refresh':j.status==='SUCCEEDED'?'check':'clock')}</div><div><div class="event-label">${escapeHTML(state.actions[j.action]?.label||j.action)}</div><div class="event-sub">${fmtDate(j.started_at)} · ${escapeHTML(j.status)}</div></div><button class="job-link" data-job="${escapeHTML(j.id)}">View log</button></div>`).join(''):`<div class="event"><div class="event-circle muted">${icon('clock')}</div><div><div class="event-label">No operations yet</div><div class="event-sub">Run a validation suite or capture a market-data sample.</div></div></div>`; }
function viewOverview(o) {
 const f=o.forward||{};
 const noPaper=f.evidence_state==='NOT_FROZEN';
 const paperRows=f.complete_forward_bars>0 && f.strategies ? `<div class="table-wrap"><table class="data-table"><thead><tr><th>PAPER STRATEGY</th><th>HYPOTHETICAL NAV</th><th>RETURN</th><th>FILLS</th></tr></thead><tbody>${Object.entries(f.strategies).map(([name,v])=>`<tr><td class="asset-symbol">${escapeHTML(name)}</td><td class="mono">${numeric(v.hypothetical_nav,2)}</td><td class="mono">${(Number(v.hypothetical_return)*100).toFixed(3)}%</td><td>${numeric(v.paper_fills)}</td></tr>`).join('')}</tbody></table></div>` : emptyPanel('No verified live portfolio P&L','Your paper strategy performance will appear here as new observations accrue.');
 return `${ribbon()}${mainStats(o)}
 <div class="section-grid"><section class="panel">${panelHeader('Portfolio performance','Precommitted forward observations · No live brokerage',statusTag('PENDING',noPaper?'NOT INITIALIZED':'FORWARD ONLY'))}
 <div class="panel-body">${paperRows}
 <div class="plot-footer"><span>${escapeHTML(f.evidence_state||'UNAVAILABLE')}</span><span>Historic simulated profits ≠ investable profits</span></div></div></section>
 <section class="panel">${panelHeader('System activity','Latest validated local operations',`<button class="btn btn-quiet" data-page="operations">View all ${icon('arrow')}</button>`)}<div class="panel-body slim">${recentJobs(o)}</div></section></div>
 <div class="section-grid"><section class="panel">${panelHeader('Quick launch','Predefined actions, no trading permissions')}
 <div class="panel-body card-stack"><div class="action-tile"><div class="action-symbol">${icon('shield')}</div><div><h3>System self-test</h3><p>Validate risk, accounting, market-data and strategy code</p></div><button class="btn btn-outline" data-action="tests">Run tests</button></div>
 <div class="action-tile"><div class="action-symbol">${icon('play')}</div><div><h3>Start paper monitoring</h3><p>Freeze a new experiment if needed, process the next precommitted step, and enable hourly checks while the server runs</p></div><button class="btn btn-primary" data-action="paper_start">Start paper</button></div>
 <div class="action-tile"><div class="action-symbol">${icon('activity')}</div><div><h3>Capture real market data</h3><p>30-second public Level 2 feed · no exchange account</p></div><button class="btn btn-outline" data-action="l2_capture">Capture</button></div>
 <div class="action-tile"><div class="action-symbol">${icon('brain')}</div><div><h3>Quant strategy laboratory</h3><p>Run offline models and benchmark comparisons</p></div><button class="btn btn-outline" data-action="omega">Research</button></div></div></section>
 <section class="panel">${panelHeader('Activation path','Account setup and risk gates')}
 <div class="panel-body"><div class="details-list"><div class="detail-row"><span>Local engine</span>${statusTag('COMPLETE','READY')}</div><div class="detail-row"><span>Data source</span>${statusTag(o.series.every(s=>s.present)?'COMPLETE':'PENDING',o.series.every(s=>s.present)?'AVAILABLE':'INCOMPLETE')}</div><div class="detail-row"><span>Broker authorization</span>${statusTag(o.broker_connected?'COMPLETE':'PENDING',o.broker_connected?'READ ONLY':'NOT LINKED')}</div><div class="detail-row"><span>Funding & payment</span>${statusTag('PENDING','EXTERNAL')}</div><div class="detail-row"><span>Live order gateway</span>${statusTag('NOT_AVAILABLE','LOCKED')}</div></div>
 <div style="margin-top:18px"><button class="btn btn-primary" data-page="setup">Open setup wizard ${icon('arrow')}</button></div></div></section></div>`;
}
function viewMarkets(o) {const rows=o.series.map((m,i)=>`<tr><td><div class="asset-symbol">${escapeHTML(m.symbol)}</div><div class="asset-sub">Coinbase · Completed 1h candles</div></td><td>${m.present?statusTag('COMPLETE','LOCAL DATA'):statusTag('PENDING','MISSING')}</td><td class="mono">${m.size_bytes?numeric(m.size_bytes)+' B':'—'}</td><td class="mono">${escapeHTML((m.last_record||'—').slice(0,80))}</td></tr>`).join('');return `${ribbon()}
 <div class="metrics-grid">${metric('Markets monitored','2','BTC-USD and ETH-USD','activity')}${metric('Locally available',String(o.series.filter(s=>s.present).length),'Historical datasets','database')}${metric('L2 captures',String(o.market_captures.length),'Recent local raw journals','terminal')}${metric('Available disk',numeric(o.disk_free_gb,1)+' GB','Local disk headroom','shield')}</div>
 <div class="panel">${panelHeader('Market data warehouse','Local historical OHLCV and captured public order-book events',statusTag('COMPLETE','READ ONLY'))}<div class="table-wrap"><table class="data-table"><thead><tr><th>INSTRUMENT</th><th>DATA STATE</th><th>FILE SIZE</th><th>LAST STORED ROW</th></tr></thead><tbody>${rows}</tbody></table></div></div>
 <div class="section-title"><h2>Data operations</h2></div><div class="op-list"><div class="op"><div class="op-top">${icon('refresh')}${statusTag('COMPLETE','PUBLIC')}</div><strong>Refresh historical data</strong><p>Append fully completed hourly candles for BTC and ETH. Refuse conflicting revisions.</p><button data-action="data" class="btn btn-primary">Update datasets ${icon('arrow')}</button></div><div class="op"><div class="op-top">${icon('activity')}${statusTag('COMPLETE','30 SECONDS')}</div><strong>Read-only Level 2 capture</strong><p>Use the public Coinbase Advanced WebSocket. Capture and preserve messages for replay.</p><button data-action="l2_capture" class="btn btn-outline">Start capture ${icon('play')}</button></div></div>
 <div class="section-title"><h2>Recent capture journals</h2></div><div class="panel"><div class="panel-body">${o.market_captures.length?o.market_captures.map(x=>`<div class="detail-row"><span>${escapeHTML(x.name)}</span><strong>${numeric(x.bytes)} bytes</strong></div>`).join(''):'<div class="small-copy">No GUI-initiated captures recorded yet. Capture a short session to begin.</div>'}</div></div>`;}
function viewStrategies(o) {const reports=o.reports; const arr=[['tournament','Quantitative portfolio tournament','Nine rule-based configurations, cost-sensitive evaluation'],['ml','Cross-asset ML','Pooled local regression models and chronological evaluation'],['swarm','Adaptive shadow swarm','Online expert weighting, simulation only'],['stress','Execution stress diagnostics','Fees, slippage, liquidity and risk sensitivity']];return `${ribbon()}<div class="section-grid"><section class="panel">${panelHeader('Strategy registry','Actual files from your local research runs')}<div class="panel-body">${arr.map(([k,title,desc])=>`<div class="event"><div class="event-circle ${reports[k].present?'':'muted'}">${icon('brain')}</div><div><div class="event-label">${title}</div><div class="event-sub">${desc}</div></div>${statusTag(reports[k].present?'COMPLETE':'PENDING',reports[k].present?'REPORT SAVED':'NOT RUN')}</div>`).join('')}</div></section><section class="panel">${panelHeader('Model deployment policy','Training results are not automatic trading permissions')}<div class="panel-body"><div class="notice"><strong>Go / no-go:</strong> No model has independently demonstrated stable after-cost profitability on genuine unseen forward data. Paper-mode strategy investigation is available; live promotion is locked.</div><div class="subtle-rule"></div><div class="details-list"><div class="detail-row"><span>Frozen forward observations</span><strong>${numeric(o.forward.complete_forward_bars||0)}</strong></div><div class="detail-row"><span>ML candidate selection</span><strong>${escapeHTML(String(reports.ml.selected||'None'))}</strong></div><div class="detail-row"><span>Real-money strategy approval</span>${statusTag('NOT_AVAILABLE','NONE')}</div></div></div></section></div><div class="section-title"><h2>Research execution</h2></div><div class="op-list"><div class="op"><div class="op-top">${icon('brain')}${statusTag('COMPLETE','LOCAL')}</div><strong>Run complete quant evaluation</strong><p>Historical portfolio tournament, cross-market models, stress tests, and pairs hypotheses. Results remain retrospective.</p><button class="btn btn-primary" data-action="omega">Launch research ${icon('arrow')}</button></div><div class="op"><div class="op-top">${icon('shield')}${statusTag('COMPLETE','PAPER')}</div><strong>Advance forward ledger</strong><p>Commit or evaluate only genuinely timestamped next-open paper intents. Requires an existing frozen experiment.</p><button class="btn btn-outline" data-action="forward">Run forward step ${icon('arrow')}</button></div></div>`;}
function viewOperations(o) {return `${ribbon()}<div class="panel">${panelHeader('Automated paper observation','Runs hourly while this local web app stays open',statusTag(o.setup.paper_schedule_enabled?'COMPLETE':'PENDING',o.setup.paper_schedule_enabled?'ENABLED':'OFF'))}
 <div class="panel-body"><p class="small-copy">Runs at approximately minute :02 UTC after a completed hourly candle. The browser may close, but the underlying Python service must stay running. No backfilled paper fills or live orders are permitted. Requires an already frozen forward experiment.</p><div class="button-row"><button class="btn ${o.setup.paper_schedule_enabled?'btn-danger':'btn-primary'}" data-schedule="${o.setup.paper_schedule_enabled?'false':'true'}">${o.setup.paper_schedule_enabled?'Stop paper monitor':'Start hourly paper monitor'} ${icon(o.setup.paper_schedule_enabled?'shield':'play')}</button><button class="btn btn-outline" data-action="forward">Run paper step now</button></div></div></div>
 <div class="section-title"><h2>Operations library</h2><span class="section-helper">One operation at a time · Durably logged</span></div><div class="op-list">${Object.entries(state.actions).map(([key,action])=>`<div class="op"><div class="op-top">${icon(key==='tests'?'shield':key.includes('l2')?'activity':'terminal')}${statusTag(key==='l2_capture'?'PENDING':'COMPLETE',key==='l2_capture'?'NETWORK':'LOCAL')}</div><strong>${escapeHTML(action.label)}</strong><p>${escapeHTML({tests:'Runs the complete offline Python test suite.',omega:'Benchmark all quant strategies, ML and risk stress.',forward:'Observe future paper intents and update the local ledger.',data:'Refresh the two public hourly OHLCV datasets.',risk_smoke:'Execute the synthetic broker + independent risk smoke scenario.',l2_smoke:'Verify L2 ingest, isolated risk and broker recovery.',l2_capture:'Capture 30 seconds of real, public Level 2 quotes.'}[key])}</p><button class="btn btn-outline" data-action="${key}">Run ${icon('arrow')}</button></div>`).join('')}</div>
 <div class="section-title"><h2>Execution history</h2><button class="btn btn-quiet" id="refresh-jobs">Refresh ${icon('refresh')}</button></div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>OPERATION</th><th>STARTED</th><th>STATUS</th><th>RESULT</th><th>LOG</th></tr></thead><tbody>${(o.jobs||[]).length ? o.jobs.map(j=>`<tr><td><strong>${escapeHTML(state.actions[j.action]?.label||j.action)}</strong></td><td>${fmtDate(j.started_at)}</td><td>${statusTag(j.status)}</td><td>${j.exit_code===null?'—':escapeHTML(j.exit_code)}</td><td><button class="job-link" data-job="${escapeHTML(j.id)}">Inspect →</button></td></tr>`).join(''):'<tr><td colspan="5" class="small-copy">No jobs have been executed yet.</td></tr>'}</tbody></table></div></div>`;}
function viewBroker(o) {
 const b=o.broker_readonly||{};
 const connected=b.connected===true;
 const snap=state.brokerSnapshot;
 const fields=connected?`<div class="details-list"><div class="detail-row"><span>Dhan profile</span><strong>${escapeHTML(b.client_id_masked||'Verified')}</strong></div><div class="detail-row"><span>Activated segments</span><strong>${escapeHTML(b.active_segments||'Unknown')}</strong></div><div class="detail-row"><span>Token validity (Dhan)</span><strong>${escapeHTML(b.token_valid_until||'Check on Dhan Web')}</strong></div><div class="detail-row"><span>Credential retention</span><strong>Process memory only</strong></div></div><div class="broker-buttons"><button class="btn btn-primary" id="fetch-broker">Refresh real account snapshot ${icon('refresh')}</button><button class="btn btn-outline" id="disconnect-broker">Disconnect</button></div>`:
 `<form id="broker-connect-form" autocomplete="off"><div class="field"><label for="dhan-client">Dhan client ID</label><input id="dhan-client" required pattern="[0-9]{5,24}" autocomplete="off" placeholder="Your numeric Dhan client ID" maxlength="24"></div><div class="field"><label for="dhan-token">Access token (24-hour)</label><input id="dhan-token" required type="password" minlength="16" autocomplete="off" spellcheck="false" placeholder="Paste fresh token from Dhan Web"></div><small class="section-helper">Sent only to this loopback Python server, then used to call Dhan GET /profile. Never stored in SQLite or job logs. The broker-issued token may itself permit trading even though Alpha_OTO never uses those endpoints.</small><div class="broker-buttons"><button class="btn btn-primary" type="submit">Verify and connect ${icon('check')}</button><a class="btn btn-outline" href="https://web.dhan.co/" target="_blank" rel="noopener noreferrer">Open Dhan Web ↗</a></div></form>`;
 const data=snap?`<div class="metrics-grid broker-metrics">${metric('Available balance','₹'+numeric(snap.available_balance,2),'Dhan fund limit at snapshot','database')}${metric('Utilized','₹'+numeric(snap.utilized,2),'Broker-reported funds used','activity')}${metric('Holdings',numeric(snap.holdings.total),'Demat positions','brain')}${metric('Orders today',numeric(snap.orders.total),'Broker orders, including external orders','terminal')}</div><div class="panel">${panelHeader('Broker portfolio snapshot','Fetched on demand · ${escapeHTML(snap.as_of_utc)}',statusTag('COMPLETE','READ ONLY'))}<div class="table-wrap"><table class="data-table"><thead><tr><th>HOLDING</th><th>SHARES</th><th>AVAILABLE</th><th>AVG COST</th></tr></thead><tbody>${snap.holdings.rows.length?snap.holdings.rows.map(h=>`<tr><td class="asset-symbol">${escapeHTML(h.symbol)}</td><td>${escapeHTML(h.quantity??'—')}</td><td>${escapeHTML(h.available_quantity??'—')}</td><td>₹${escapeHTML(h.avg_cost??'—')}</td></tr>`).join(''):'<tr><td colspan="4">No holdings returned</td></tr>'}</tbody></table></div></div>`:
 `<div class="panel"><div class="panel-body">${emptyPanel('No account snapshot loaded',connected?'Click Refresh real account snapshot; data is never refreshed without your request.':'Connect a valid Dhan account to inspect holdings and account balances.')}</div></div>`;
 return `${ribbon()}<div class="section-grid"><section class="panel">${panelHeader('DhanHQ account link','Official broker access token verified against Dhan /v2/profile',statusTag(connected?'COMPLETE':'PENDING',connected?'READ-ONLY CONNECTED':'NOT CONNECTED'))}<div class="panel-body">${fields}</div></section><section class="panel">${panelHeader('Activation and payments','Complete these steps only on official provider websites')}<div class="panel-body"><div class="step-item"><span class="step-marker done">1</span><div><div class="step-name">Open an approved Dhan account</div><div class="step-desc">KYC, identity confirmation and banking are completed on Dhan Web.</div></div></div><div class="step-item"><span class="step-marker ${connected?'done':''}">2</span><div><div class="step-name">Generate a 24-hour DhanHQ token</div><div class="step-desc">Dhan Web → Profile → Access DhanHQ APIs; new token required after expiry.</div></div></div><div class="step-item"><span class="step-marker">3</span><div><div class="step-name">Fund on the broker website</div><div class="step-desc">Alpha_OTO has no payment, deposit or withdrawal integration; confirm actual broker balances before drawing conclusions.</div></div></div><div class="step-item"><span class="step-marker">4</span><div><div class="step-name">Market data subscription, if needed</div><div class="step-desc">Optional provider-charged market-data plan; verify current price directly with Dhan before purchasing.</div></div></div><div class="step-item"><span class="step-marker">5</span><div><div class="step-name">Live brokerage execution</div><div class="step-desc">LOCKED pending brokerage permissions, audited risk enforcement and independent strategy evidence.</div></div></div><a class="btn btn-outline" href="https://web.dhan.co/" target="_blank" rel="noopener noreferrer">Manage funding and APIs at Dhan ↗</a></div></section></div>${data}<div class="notice blue"><strong>Security boundary:</strong> This connection allows viewing real account data through broker GET APIs. Dhan-issued access tokens are not guaranteed to be limited to read-only use. Use the dashboard only on your trusted Mac; do not expose localhost through tunnels or reverse proxies. Alpha_OTO cannot transfer money or submit live orders.</div>`;
}
function viewSetup(o) {const s=o.setup;const complete=s.steps.filter(x=>x.state==='COMPLETE').length;return `${ribbon()}<div class="section-grid"><div class="workflow-card"><div class="eyebrow">ONBOARDING / STEP BY STEP</div><h2>Build a verified trading setup.</h2><p>The interface will guide you through market selection, local data, forward simulation, external broker identity verification, fees and approvals. It does not collect brokerage passwords, bank details or payments.</p><div style="display:flex;justify-content:space-between;gap:10px;margin-top:19px;font-size:11px"><span>Setup milestones</span><strong>${complete} of ${s.steps.length} complete</strong></div><div class="progress-track"><div class="progress-fill" style="width:${Math.round(complete/s.steps.length*100)}%"></div></div></div>
 <section class="panel">${panelHeader('Connection status','Explicitly unconnected until independently validated')}<div class="panel-body"><div class="details-list"><div class="detail-row"><span>Broker account</span>${statusTag('PENDING','NOT LINKED')}</div><div class="detail-row"><span>Identity / KYC</span>${statusTag('PENDING','EXTERNAL')}</div><div class="detail-row"><span>Paid data and subscriptions</span>${statusTag('PENDING','NOT PURCHASED')}</div><div class="detail-row"><span>Deposits and withdrawals</span>${statusTag('NOT_AVAILABLE','DISABLED')}</div><div class="detail-row"><span>Live orders</span>${statusTag('NOT_AVAILABLE','DISABLED')}</div></div></div></section></div>
 <div class="section-grid"><section class="panel">${panelHeader('1. Local product preferences','These settings do not establish broker connectivity')}<div class="panel-body"><form id="setup-form"><div class="field"><label for="market">Primary market to pursue</label><select name="market" id="market"><option value="undecided">Select a market</option><option value="india_cash_equities">Indian cash equities</option><option value="crypto_spot">Crypto spot</option><option value="global_cash_equities">Global cash equities</option></select><small>Legality, exchange access and applicable settlement rules require separate review.</small></div><div class="field"><label for="broker">Potential broker (selection only)</label><select name="broker" id="broker"><option value="undecided">No broker selected</option><option value="dhan">Dhan — Indian markets</option><option value="ibkr">Interactive Brokers — international cash markets</option><option value="other">Other / to be evaluated</option></select><small>This saves a preference only. Dhan authentication is on the separate Dhan account page; token is kept in process memory only.</small></div><div class="field"><label for="budget">Illustrative simulated account budget</label><input id="budget" type="number" min="100" max="10000000" step="100" value="10000" inputmode="decimal"><small>Paper-only amount. This does not allocate, deposit or reserve money.</small></div><button class="btn btn-primary" type="submit">Save preferences ${icon('check')}</button></form></div></section><section class="panel">${panelHeader('2. Launch readiness','Every gate must be satisfied independently')}<div class="panel-body">${s.steps.map((item,i)=>`<div class="step-item"><span class="step-marker ${item.state==='COMPLETE'?'done':''}">${item.state==='COMPLETE'?icon('check'):i+1}</span><div><div class="step-name">${escapeHTML(item.title)}</div><div class="step-desc">${escapeHTML(item.id==='funding'?'Use official provider checkout externally; do not send payment details here.':item.id==='identity'?'Verify directly with the selected regulated broker.':item.id==='approval'?'Independent suitability, security, integration and performance gates.':'Documented local prerequisite')}</div></div>${statusTag(item.state)}</div>`).join('')}</div></section></div>
 <div class="notice blue"><strong>Payments and account authentication:</strong> Dhan account verification is available on the Dhan account page using a 24-hour token. KYC, paid market-data subscriptions and deposits are handled by Dhan on its official site. Live trading remains locked. Any future live activation will require explicit, separate operator approval.</div>`;}
const pages={overview:['Control center','One interface for your models, data, and simulated operations.','01'],markets:['Market data','Historical price data, real-time ingestion, and feed integrity.','02'],strategies:['Strategy laboratory','Compare evidence before considering real capital.','03'],operations:['Operations','Execute, monitor, and audit local tasks.','04'],broker:['Dhan account','Verify an official account and inspect real holdings without trading.','05'],setup:['Setup & connections','Configure this machine and understand what remains to go live.','06']};
function render() {const o=state.overview;if(!o)return;const info=pages[state.page];$('#crumb-current').textContent=state.page==='overview'?'Overview':info[0];$('.page-heading h1').innerHTML=escapeHTML(info[0])+'<span class="period">.</span>';$('.page-heading .eyebrow').innerHTML=`OPERATOR CONSOLE <span class="eyebrow-slash">/</span> ${info[2]}`;$('.page-heading p').textContent=info[1];document.querySelectorAll('[data-page]').forEach(el=>{if(el.classList.contains('nav-item'))el.classList.toggle('active',el.dataset.page===state.page)});$('#job-count').textContent=String(o.jobs.filter(j=>j.status==='RUNNING').length);$('#screen').innerHTML=({overview:viewOverview,markets:viewMarkets,strategies:viewStrategies,operations:viewOperations,broker:viewBroker,setup:viewSetup}[state.page])(o);if(state.page==='setup'){ $('#market').value=o.setup.market;$('#broker').value=o.setup.broker;$('#budget').value=o.setup.paper_budget; }}
async function refresh(quiet=false) { try { state.overview=await get('/api/overview');state.setup=state.overview.setup;render();if(!quiet)toast('Workspace refreshed'); } catch(e) {if(!quiet)toast(e.message,true);} }
async function launch(action) { const name=state.actions[action]?.label||action;if(!confirm(`Start ${name}?\n\nThis action is restricted to offline research or paper-mode operations. No live trades will be placed.`))return;try{const j=await post('/api/jobs',{action});toast(`${name} started. Open its log from Operations.`);await refresh(true);await showJob(j.job_id);}catch(e){toast(e.message,true);} }
async function showJob(id){try{const j=await get('/api/job?id='+encodeURIComponent(id));state.openJob=id;$('#modal-title').textContent=state.actions[j.action]?.label||j.action;$('#modal-status').textContent=`${j.status} · Started ${fmtDate(j.started_at)}${j.exit_code===null?'':` · Exit ${j.exit_code}`}`;$('#job-output').textContent=j.output||'Job is running; no output available yet.';$('#job-modal').classList.remove('hidden');}catch(e){toast(e.message,true)}}
function closeModal(){state.openJob=null;$('#job-modal').classList.add('hidden');}
async function saveSetup(evt){evt.preventDefault();const body={market:$('#market').value,broker:$('#broker').value,paper_budget:Number($('#budget').value)};try{await post('/api/setup',body);toast('Local preferences saved. No external connection was made.');await refresh(true);}catch(e){toast(e.message,true)}}
async function connectDhan(evt){evt.preventDefault();const client=$('#dhan-client').value.trim();const token=$('#dhan-token').value.trim();$('#dhan-token').value='';try{await post('/api/broker/connect',{client_id:client,token});state.brokerSnapshot=null;toast('Dhan identity verified. Broker calls are read-only.');await refresh(true);}catch(e){toast(e.message,true);}}
async function fetchDhan(){try{state.brokerSnapshot=await post('/api/broker/snapshot',{});toast('Broker snapshot updated using GET-only API.');await refresh(true);}catch(e){state.brokerSnapshot=null;toast(e.message,true);await refresh(true);}}
async function disconnectDhan(){try{await post('/api/broker/disconnect',{});state.brokerSnapshot=null;toast('Dhan session disconnected.');await refresh(true);}catch(e){toast(e.message,true);}}
async function switchSchedule(bool){try{const j=await post('/api/scheduler',{enabled:bool});toast(bool?'Paper monitoring scheduled while app runs':'Paper monitoring disabled');await refresh(true);}catch(e){toast(e.message,true)}}
document.addEventListener('click',e=>{const page=e.target.closest('[data-page]');if(page){state.page=page.dataset.page;render();window.scrollTo({top:0,behavior:'smooth'});return}const action=e.target.closest('[data-action]');if(action){launch(action.dataset.action);return}const job=e.target.closest('[data-job]');if(job){showJob(job.dataset.job);return}const schedule=e.target.closest('[data-schedule]');if(schedule){switchSchedule(schedule.dataset.schedule==='true');return}if(e.target.id==='fetch-broker'){fetchDhan();return}if(e.target.id==='disconnect-broker'){disconnectDhan();return}if(e.target.id==='refresh'||e.target.closest('#refresh')||e.target.closest('#refresh-jobs')){refresh();return}if(e.target.id==='close-modal'||e.target.id==='close-modal-bottom'||e.target.id==='job-modal'){closeModal();return}});
document.addEventListener('submit',e=>{if(e.target.id==='setup-form')saveSetup(e);if(e.target.id==='broker-connect-form')connectDhan(e)});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
(async()=>{try{const boot=await get('/api/bootstrap');state.csrf=boot.csrf;state.actions=boot.actions;await refresh(true);}catch(e){$('#screen').innerHTML=`<div class="notice"><strong>Local authentication required.</strong> ${escapeHTML(e.message)}<div style="margin-top:12px">Reopen the private URL printed by the launch command in your Terminal.</div></div>`;}})();
setInterval(()=>{const el=$('#utc-clock');if(el)el.textContent=new Date().toISOString().slice(11,19)+' UTC';},1000);
setInterval(()=>{if(state.csrf && !['broker','setup'].includes(state.page))refresh(true);if(state.openJob)showJob(state.openJob);},10000);
